### ISSUE TITLE
能否结合一下Spring Security弄个动态权限管理？

### ISSUE THREAD

**Issue by qq12157138** [ustcwudi/SpringBoot-Seed#5]
基于现在的例子能否结合一下Spring Security弄个动态权限管理？
没有思路 不知道从哪下手

**Comment by ustcwudi** [comment]
看SecurityUser类，可以通过设置GrantedAuthority集合来控制权限，权限具体怎么用需要自己灵活操作

**Comment by ustcwudi** [comment]
参考SpringBoot-Seed-Service/src/main/java/com/wind/service/config/OAuthConfiguration.java的代码

		http
				.authorizeRequests()
				.antMatchers("/").permitAll()
				.antMatchers("/v2/**","/swagger**", "/druid/**").permitAll()
				.antMatchers("/api/**").hasAuthority("user")
				.anyRequest().authenticated();

**Comment by qq12157138** [comment]
这是在代码中指定了某些用户的权限，并没有进行角色划分（角色是不是就admin和user这两个固定的？） 和 动态管理，根据数据库中的授权进行访问某些资源

**Comment by qq12157138** [comment]
@ustcwudi 这是在代码中指定了某些用户的权限，并没有进行角色划分（角色是不是就admin和user这两个固定的？） 和 动态管理，根据数据库中的授权进行访问某些资源
